custom_logo: "/home/ccarlos/repos/metagenomics-nf/assets/Logo-IATA-CSIC.png"
title: "Metagenomics"
subtitle: "Quality Report"
comment: "Estudio de prueba para testar la pipeline"
extra_fn_clean_exts:
  - ".standard.kraken2.report"
  - ".standard"
  - "."
  - "_"
top_modules:
 - "trimmomatic":
      path_filters:
       - "*.trimlog.out"
 - "bowtie2":
      name: "bowtie2 to remove human reads"
 - "kraken":
      name: "Kraken2"
      path_filters:
       - "*.kraken2.report"
 - "fastqc":
      name: "FastQC Before Trimming"
      info: "This section shows the module with different files"
      path_filters_exclude:
       - ".trimmed_fastqc."
       - ".trimmed.single_fastqc."
 - "fastqc":
      name: "FastQC Paired After Trimming"
      path_filters_exclude:
       - ".trimmed.single_fastqc."
 - "fastqc":
      name: "FastQC Unpaired After Trimming"
      path_filters_exclude:
       - ".trimmed_fastqc."